### ISSUE TITLE
[feature request] Add support for AWS LightSail (less-expensive alternative to EC2)

### ISSUE THREAD

**Issue by emveeoh** [ttlequals0/autovpn#12]
[feature request]
Add support for AWS LightSail (less-expensive alternative to EC2).

**Comment by ttlequals0** [comment]
This defeats the purpose of the project. This is meant to be an on demand OpenVPN Endpoint on AWS solution.

**Comment by emveeoh** [comment]
LightSail is AWS. It has full access to all AWS offerings. It is just a cheaper/easier EC2 container and was created as direct competition to Digital Ocean. All prices on LightSail are fixed and not open-ended like EC2 containers.

**Comment by igormatkovic** [comment]
Since i was using the VPN to transfer large amounts of data.. Lightsail is the best option for me.


To get autovpn working on Lightsail is pretty easy.


Go TO Lightsail.

First go to Account and create your default KEY.
Download the Key to your computer and add it to your .ssh/ directory
```bash
chmod 400 mykey.pem
```
Also add your key to the ssh agent
```bash
ssh-add mykey.pem
```

On Lightsail click Create New Instance
Select OS Only and Ubuntu 16.04
Select the 5$ instance
Make sure the default key is selected
And click create

Wait till it boots up.

On the instance tab select Networking

Open the Firewall Port 
```bash
Custom UDP 1194
```

Log in to your instance from the terminal
```bash
ssh -i .ssh/mykey.pem ubuntu@instance-ip
```


Download the install part of autovpn to the server and execute it
```bash
wget https://raw.githubusercontent.com/ttlequals0/autovpn/master/scripts/openvpn-autoinstall.sh && sudo bash ./openvpn-autoinstall.sh 
```



When the script is done. You should have a new file generated:
```bash
/root/aws_vpn.ovpn
```

Copy over the file to your local machine and start using your VPN

```bash
sudo openvpn download_vpn.ovpn
```
